dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
services:
  - postgresql
addons:
  apt:
    packages:
      - postgresql-server-dev-9.6
script: bundle exec rake test
before_install:
  - git clone https://github.com/HypoPG/hypopg.git
  - cd hypopg
  - git checkout 1.1.2
  - make
  - sudo make install
  - createdb dexter_test
notifications:
  email:
    on_success: never
    on_failure: change
