dist: bionic
language: ruby
rvm: 2.7
gemfile:
  - Gemfile
services:
  - postgresql
addons:
  postgresql: 10
apt:
  packages:
    - postgresql-server-dev-10
script: bundle exec rake test
before_install:
  - git clone https://github.com/HypoPG/hypopg.git
  - cd hypopg
  - git checkout 1.1.3
  - make
  - sudo make install
  - createdb dexter_test
notifications:
  email:
    on_success: never
    on_failure: change
